#
# Changes to this file will be overwritten by `trmnlp pull`.
#
# Docs: https://help.usetrmnl.com/en/articles/10542599-importing-and-exporting-private-plugins#h_581fb988f0
#
---
strategy: polling
refresh_interval: 900
polling_verb: get
polling_url: https://raw.githubusercontent.com/vhurdaneta/trmnl-currency-plugin/master/data/output.json
